// Twitch Emote regexes

var processEmoteRegExp = function(str) {
	// Robot emotes
	str = str.replace(/&lt;3\b/g, 
		'<img src="/emotes/-robot/heart.png" alt="&lt;3" title="&lt;3" class="emote">');
	// -global emotes
	str = str.replace(/\b(JKanStyle|OptimizePrime|StoneLightning|TheRinger|RedCoat|Kappa|JonCarnage|MrDestructoid|BCWarrior|GingerPower|DansGame|SwiftRage|PJSalt|KevinTurtle|Kreygasm|SSSsss|PunchTrees|ArsonNoSexy|SMOrc|FrankerZ|OneHand|HassanChop|BloodTrail|DBstyle|AsianGlow|BibleThump|ShazBotstix|PogChamp|PMSTwin|FUNgineer|ResidentSleeper|4Head|HotPokket|FailFish|DAESuppy|WholeWheat|ThunBeast|TF2John|RalpherZ|Kippa|Keepo|BigBrother|SoBayed|PeoplesChamp|GrammarKing|PanicVis|ANELE|BrokeBack|PipeHype|YouWHY|RitzMitz|EleGiggle|TheThing|HassaanChop|BabyRage|panicBasket|PermaSmug|BuddhaBar|WutFace|PRChase|Mau5|HeyGuys|NotATK|mcaT|TTours|PraiseIt|HumbleLife|CorgiDerp|ArgieB8|ShadyLulu|KappaPride|CoolCat|DendiFace|NotLikeThis|riPepperonis|duDudu|bleedPurple|twitchRaid|SeemsGood|MingLee|KappaRoss|KappaClaus|OhMyDog|OSFrog|SeriousSloth|KomodoHype|VoHiYo|MikeHogu|KappaWealth|cmonBruh|SmoocherZ|NomNom|StinkyCheese|ChefFrank|FutureMan|OpieOP|DoritosChip|PJSugar|VoteYea|VoteNay|RuleFive|DxCat|DrinkPurple|TinyFace|PicoMause|TheTarFu|DatSheffy|UnSane|copyThis|pastaThat|imGlitch|GivePLZ|TakeNRG|BlargNaut|DogFace|Jebaited|TooSpicy|WTRuck|UncleNox|RaccAttack|StrawBeary|PrimeMe|BrainSlug|BatChest|CurseLit|Poooound|FreakinStinkin|SuperVinlin|TriHard|CoolStoryBob|ItsBoshyTime|KAPOW|YouDontSay|UWot|RlyTho|PartyTime|NinjaGrumpy|MVGame|TBAngel|TheIlluminati|BlessRNG|MorphinTime|ThankEgg|ArigatoNas|BegWan|BigPhish|InuyoFace|Kappu|KonCha|PunOko|SabaPing|TearGlove|TehePelo|TwitchLit|CarlSmile|CrreamAwk|Squid1|Squid2|Squid3|Squid4|TwitchUnity|TPcrunchyroll|EntropyWins|LUL|PowerUpR|PowerUpL|HSCheers|HSWP|DarkMode|TwitchVotes|TPFufun|RedTeam|GreenTeam|HappyJack|AngryJack|PurpleStar|FBtouchdown|PopCorn|TombRaid|EarthDay|PartyHat|MercyWing1|MercyWing2|PinkMercy|BisexualPride|LesbianPride|GayPride|TransgenderPride|AsexualPride|PansexualPride|TwitchRPG|IntersexPride|MaxLOL|NonBinaryPride|GenderFluidPride|FBRun|FBPass|FBSpiral|FBBlock|FBCatch|FBChallenge|FBPenalty|PeteZaroll|PeteZarollOdyssey|PixelBob|GunRun|HolidayCookie|HolidayLog|HolidayOrnament|HolidayPresent|HolidaySanta|HolidayTree|SoonerLater)\b/g,
		'<img src="/emotes/-global/$&.png" alt="$&" title="$&" class="emote"/>');
	// puncayshun emotes
	str = str.replace(/\b(punWaifu|punPeach|punLewd|punDokuro|punCirno|punGasm|punW|punEhhUrr|punWhomp|punOK|punTHICC|punGayshun|punThrow|punWW|punWWW|punK|punB|punThump|punC|punChamp)\b/g,
		'<img src="/emotes/puncayshun/$&.png" alt="$&" title="$&" class="emote"/>');
	// cirno_tv emotes
	str = str.replace(/\b(cirFairy|cirGPantsu|cirLPantsu|cirSmug|cirAYAYA|cirBaka|cirBlech|cirBless|cirBlind|cirCola|cirComfy|cirCop|cirD|cirDerp|cirGasm|cirGreed|cirHappy|cirHi|cirHonk|cirHuh|cirISee|cirKiss|cirLaugh|cirLick|cirLost|cirLove|cirMiku|cirMini|cirNilla|cirPalm|cirPat|cirPls|cirPrise|cirREE|cirShades|cirSlain|cirTan|cirThink|cirNo|cirWink|cirWut|cirLewd|cir3)\b/g,
		'<img src="/emotes/cirno_tv/$&.png" alt="$&" title="$&" class="emote"/>');
	// auslove emotes
	str = str.replace(/\b(ausRage|ausGrin|ausHax|ausLick|ausRich|ausGoof|ausDJ|ausHug|ausGG|ausTy|ausLol|ausCry|ausRekt|ausWow|ausHungry|ausTroll|ausShiny|ausPride|ausBaited|ausCute|ausGrump|ausGasm|ausL|ausChu|ausPray|aus5|ausHi|aus1|ausBroke|ausYum|ausLurk|ausWave|ausLuck|ausDab|ausEww|ausEarly|ausHype|ausTilt|ausYay|ausCheeky|ausPotato|ausPew|ausHole)\b/g,
		'<img src="/emotes/auslove/$&.png" alt="$&" title="$&" class="emote"/>');
	// twitchplayspokemon emotes
	str = str.replace(/\b(tppCrit|tppPokeyen|tppRng|tppHelix|tppRiot|tppPc|tppDome|tppSlowpoke|tppTrumpet|tppPokeball|tppBait|tppS|tppLUL|tppTeiHard|tppShiny|tppRage|tppBless|tppCool|tppPika|tppFail|tppLove|tppGlitch)\b/g,
		'<img src="/emotes/twitchplayspokemon/$&.png" alt="$&" title="$&" class="emote"/>');
	// evo emotes
	str = str.replace(/\b(evo2018|evoUSA|evoJapan|evoUK|evoKorea|evoFrance|evoMexico|evoChina|evoCanada|evoChile|evoTaiwan|evoPR|evoMindBlown|evoTilt|evoDownload|evoGhost|evoHeart|evoHiyo|evoLeftbehind|evoPride|evoShill|evoBanzai|evoGG|evoFlip|evoStick|evoCharge|evoTBC|evoWiz|evoClip|evoTape|evoMeasure|evoTech|evoKO|evoWut)\b/g,
		'<img src="/emotes/evo/$&.png" alt="$&" title="$&" class="emote"/>');
	// FrankerFaceZ emotes
	str = str.replace(/\b(tbSriracha|tbSpicy|tbQuesarito|tbBaconBiscuit|tbSausageBiscuit|tbChickenBiscuit|monikaS|MonikA|MonikaDeleteTime|MonikaSmug|SayoriHxppy|SayoriThink|SayoriXD|SayoriDX|SayoriPout|YuriBlush|YuriComfy|YuriSmug|NatsukiCute|NatsukiDX|NatsukiSmug|Thonk)\b/g,
		'<img src="/emotes/-ffz/$&.png" alt="$&" title="$&" class="emote"/>');
	// Extra emotes
	str = str.replace(/\b(AMPEnergy|AMPEnergyCherry|AMPTropPunch|Ackbar|AtGL|AtIvy|AtWW|AthenaPMS|BCouch|BJBlazkowicz|BORT|BQRT|BionicBunion|BudBlast|BudStar|ChipotleChip|CougarHunt|DOOMGuy|DatHass|Demon|DxAbomb|EagleEye|EvilFetus|Evo2013|FBEagles|FBGiants|FBJaguars|FBTitans|FPSMarksman|FeelsBadMan|FeelsGoodMan|FiteFiteFite|Fraud|FunRun|FuzzyOtterOO|GOWAtreus|GOWKratos|GOWSkull|GasJoker|GoCanada|GoChina|GoEU|GoFrance|GoJapan|GoKorea|GoMexico|GoTaiwan|GoUK|GoUSA|HSLight|HSVoid|ItsATrap|JC4gabriela|JC4hook|JC4rico|KAPOldW|KZskull|MechaSupes|NerfBlueBlaster|NerfRedBlaster|NervousMonkey|NightBat|NinjaTroll|NoNoSpot|OMGScoots|OSSmooth|OSbeaver|OSblob|OSbury|OSdeo|OSfrog|OSkomodo|OSrob|OSsloth|PJHarley|PackItUp|PazPazowitz|PeteZarollTie|PuppeyFace|QuadDamage|SGlemon|SGmouth|SGrasp|SMSkull|SOTahoy|SOTshark|SPKFace|SPKWave|Shazam|ShibeZ|SnickersBoom|SnickersGoal|Soulfist|SriHead|Stormtrooper|Sullustan|TBCheesePull|TBCrunchy|TBTacoBag|TBTacoLeft|TBTacoProps|TBTacoRight|TheKing|TriZard|TwitchRPGCoin|UleetBackup|VaultBoy|Volcania|WAHAHA|WeAreVenom|WinWaker|ausArt|ausBait|ausC|ausChamp|ausCheer|ausDono|ausFix|ausGift|ausHonk|ausMunch|ausNap|ausPoor|ausThump|ausTired|cirBar|cirBell|cirGlod|cirPumpkin|cirRage|cirSanta|cirSleep|cirThree|cirWitch|deExcite|deIlluminati|evo172017|evo17Banzai|evo17Canada|evo17Charge|evo17Chile|evo17China|evo17Clip|evo17Download|evo17Flip|evo17France|evo17GG|evo17Ghost|evo17Heart|evo17Hiyo|evo17Japan|evo17KO|evo17Korea|evo17LeftBehind|evo17Measure|evo17Mexico|evo17MindBlown|evo17PR|evo17Pride|evo17Rekt|evo17Shill|evo17Stick|evo17TBC|evo17Taiwan|evo17Tape|evo17Tech|evo17Tilt|evo17UK|evo17USA|evo17Wiz|evo17Wut|evo2015|evoKapow|evoKappaOno|evoMcRib|kappaRyu|kappaSagat|lffn21|lffnEvil|lffnLEFF|lffnMarth|lffnNotch|lffnPaint|lffnPaintGold|lffnSheik|lffnWeeb|lffnZam|mm2Nice|mm2NotNice|pun2hu|punRNG|shazamicon|tgaTrophy|tppCursor|tppFogChamp|tppHappy|tppHax|tppMiss|tppPayout|tppRobored|tppUrn)\b/g,
		'<img src="/emotes/-x/$&.png" alt="$&" title="$&" class="emote"/>');
	return str;
};
